spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://103.48.192.223:5555/postgres
    username: postgres
    password: password
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: edu.nguyenkiet0807@gmail.com
    password: phurpgnzlnpvkrsh
    port: '587'

server:
  port: 8080