spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://103.48.192.223:5555/postgres
    username: postgres
    password: password
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8080